### ISSUE TITLE
Show error in Frontend

### ISSUE THREAD

**Issue by creazy231** [creazy231/strapi-plugin-raw-query#1]

**Comment by agileago** [comment]
+1

**Comment by creazy231** [comment]
This feature comes with the release of Strapi v4 first. Maybe I'll add this feature to the v3 after.

![image](https://user-images.githubusercontent.com/13473174/136714285-5c133296-6e01-4b7e-adb2-d0db8d0292bf.png)

**Comment by creazy231** [comment]
Just released version 1.0.0 of Raw Query which includes the feature request 🚀 
https://github.com/creazy231/strapi-plugin-raw-query/releases/tag/1.0.0
