### ISSUE TITLE
Error when attempting to run query

### ISSUE THREAD

**Issue by bastianhilton** [creazy231/strapi-plugin-raw-query#3]
I get an error that states that there was an **error executing your query** when attempting to run create table commands. But it doesn't provide any indication on what is wrong. Any idea why this is happening?

**Comment by creazy231** [comment]
Sorry for the late response. Wasn't actively using this plugin on my own but I'll take a deeper look into this and try to fix this asap.

**Comment by creazy231** [comment]
fixed by commit https://github.com/creazy231/strapi-plugin-raw-query/commit/950ab5dec2698aa75cf958bdaa1b5e5f0f6398d6

please update to latest version from npm using npm or yarn. Version 1.0.5 fixes the issue
